# Generated by Django 4.2 on 2023-05-05 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quenic', '0002_alter_queue_name_queuemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
