# Generated by Django 4.2 on 2023-05-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quenic', '0003_queue_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='users',
        ),
    ]
